### PR TITLE
Allow users to select which images to return from rstudio_gallery()

### PR DESCRIPTION
**Pull request by kferris10**
Added a parameter to the rstudio_gallery() function which allows the user to select which images they want to return

### CODE REVIEW

**Comment by timelyportfolio** [comment]
Great idea.  This reminds me that the result from `list.files` will not be in time/date order, so the sequence could easily be wrong.  Also, I would think the main benefit here would be to avoid the `base64enc` piece of it.  I'll pull and then adjust slightly.

Thanks again.  `loryR` can go in all sorts of directions.  I'm glad you are using it.  Please let me know what you make with it.

**Comment by kferris10** [comment]
Do you know what order these are returned in? (Most recent to oldest or oldest to most recent?)  Ideally, I think there should be another argument like `most_recent` so that `rstudio_gallery(1:3, most_recent = TRUE)` would return the three most recent images.

Sure cool widget!  Thanks for making it.

**Comment by timelyportfolio** [comment]
Another great idea.  I think this is easy enough to handle though outside of the function with `head`, `tail`, `rev`, and other subsetting functions.  So, for instance we could do something like this.

```
loryR( head(rstudio_gallery(),3) )
```

**Comment by kferris10** [comment]
Good call.

What order do things get returned in?  When I do the first example

```
library(loryR)

# make some sample plots
plot(1:10,col="red")
contour(volcano)
lattice::xyplot(x~0:90, data.frame(x=cos(0:90/90)))

images <- rstudio_gallery()

loryR(images, width = "90%", options = list(rewind=T))
```

I see the `plot(1:10)`, then the `lattice::xyplot`, then the `countour()` plot.  Why is that happening?

**Comment by timelyportfolio** [comment]
I really am not sure of the mechanism by which RStudio saves the files nor am I convinced that order/sequence is reliable.  However, on my Windows 7 machine, if I run each plot separately, they show up in order with `rstudio_gallery()`.  If I run the whole block at once with CTRL+R, I only get one plot.  If I then hit the back button on the RStudio Plots Tab and run `rstudio_gallery()`, I get them all but in reverse order.

**Comment by kferris10** [comment]
That's really strange.  If I run the whole block, I also only get one image.  But I do get them in a different order when running one at a time.  Probably not worth worrying about again though.

Thanks again for the cool package!

**Pull request merged**
